name: coverage

on:
  push:
    branches:
      - '*'

jobs:
  codecov:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@master
  
      - name: Codecov
      - uses: codecov/codecov-action@v2.1
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
