name: Tests

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  swift-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: Pushd check
        run: which pushd

      - name: Popd check
        run: which popd

      - name: swift info
        run: swift --version

      - name: Build
        run: ./buildAll.sh

      - name: Test
        run: ./testAll.sh

      - name: Run
        run: ./runAll.sh
        